---
language: java
env:
- GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcloud-service-key.json
script:
- echo $GOOGLE_APPLICATION_CREDENTIALS
- ./gradlew run
before_install:
- openssl aes-256-cbc -K $encrypted_fb8312436011_key -iv $encrypted_fb8312436011_iv
  -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
